MONGODB_HOST: 172.31.5.197
REDIS_HOST: redis.daws86s.fun
CATALOGUE_HOST: catalogue.daws86s.fun
CART_HOST: cart.daws86s.fun
USER_HOST: user.daws86s.fun
RABBITMQ_HOST: 172.31.2.232
MYSQL_HOST: 172.31.9.248
SHIPPING_HOST: shipping.daws86s.fun
PAYMENT_HOST: payment.daws86s.fun